parameters:
  market-score:
      Ins D & Up: 2
      Ins Wk & Up: 2.5
      Ins Mo & Up: 2.75,
      Ins D: 0,
      Ins Wk: 0,
      Ins Mo: 0,
      Ins D & Dwn: -2,
      Ins Wk & Dwn: -2.5,
      Ins Mo & Dwn: -2.75,
      D Hammer: 3,
      Wk Hammer: 3.5,
      Mo Hammer: 4,
      D Shtng Star: -3,
      Wk Shtng Star: -3.5,
      Mo Shtng Star: -4.,
      D Bullish Eng: 1,
      Wk Bullish Eng: 1.5,
      Mo Bullish Eng: 2,
      D Bearish Eng: -1,
      Wk Bearish Eng: -1.5,
      Mo Bearish Eng: -2,
      D Hammer & Up: 3.75,
      D Shtng Star & Down: -3.75
