#! /bin/bash -
while (( "$#" > 0 )) ; do
  case $1 in
    bare)
      echo 'will perform bare install'
      cp .env.test .env
      # prep variables for the .env file
      echo "APP_ENV=$APP_ENV" >> .env
      echo "DATABASE_URL=\"$DATABASE_CONNECTOR\"" >> .env
      composer install
      ;;
    database)
      echo 'will create blank database and perform migrations'
      bin/console doctrine:database:create
      bin/console doctrine:migrations:migrate --no-interaction
      ;;
    fixtures)
      # include check for non-prod environment here
      # ...
      echo 'will clear out existing database and add fixtures'
#      rclone --config=$RCLONE_CONFIG copy $DATA_REMOTE:$BUCKET_NAME/data/source /var/www/html/data/source
      bin/console doctrine:fixtures:load --group=Instruments --no-interaction
      bin/console doctrine:fixtures:load --group=OHLCV1 --append --no-interaction
      bin/console doctrine:fixtures:load --group=OHLCV2 --append --no-interaction
      ;;
    tests)
      echo 'will run unit tests'
      bin/phpunit tests/Service/Exchange/DailyIteratorTest.php
      bin/phpunit tests/Service/Exchange/WeeklyIteratorTest.php
      bin/phpunit tests/Service/Exchange/MonthlyIteratorTest.php
      bin/phpunit tests/Service/Exchange/Equities
      bin/phpunit tests/Service/PriceHistory/OHLCV
      bin/phpunit tests/Service/Scanner/OHLCV
      ;;
    data)
      echo 'will copy application data from aws'
      rclone --config=$RCLONE_CONFIG copy $DATA_REMOTE:$BUCKET_NAME/data/source /var/www/html/data/source
      bin/console instruments:import -v --clear-db=true
      bin/console price:import -v --provider=YAHOO
      ;;
    audits)
      echo 'run audits on data'
      bin/console price:audit -v --provider=YAHOO
      ;;
    *) echo "invalid directive $1"
      ;;
  esac
  shift
done

## Include bash scripts to formulate y_universe and lists for nyse, amex, and nasdaq
## ...
