#! /bin/sh -
#usage: script <y_universe.src(new)> <Market\ Survey_1601.csv(existing)> 
#description: 
# The script takes the Y_Universe source file which contains symbols and other data for 12 sectors maintained by Spiders (SPDR) and updates the Y_Universe spreadsheet.
# Preliminary steps that must be done manually:
# a) Download 12 .xls files for each sector symbol from www.spdrs.com/product (use link "US Equities")
# On Linux you can also use a curl call. For example, to download holdings for XLU use:
# curl -o XLU.xlsx -GL https://www.ssga.com/us/en/individual/etfs/library-content/products/fund-data/etfs/us/holdings-daily-us-en-xlu.xlsx
# b) Copy and paste all columns from the .xls files into one .csv master file titled y_universe.src. You can use existing .src file as an example, but if you loose it, it contains 6 columns in this order: Name, Symbol, Weight, Industry, Shares Held, SPDR Fund.
# c) When you initially run this script, it will list lines that might contain illegal symbols (reserved records for example). If this happens, check the symbols to be the same as in TC2000, then go back to the y_universe.src and make adjustments. Do not erase the file check_symbols.tmp when you are sure all corrections/adjustments have been finished.
# d) The script outputs file Y_Universe.csv, which is ready for pasting into the spreadsheet. The output file will only contain the data columns up to the earnngs data. The formulas must be adjusted in the spreadsheet.
file1="check_symbols.tmp"
file2="$1"
file3="$2"
file4="y_universe.tmp"
file5="new.tmp"
file6="old.tmp"
file7="market_survey.tmp"
file8="delta.tmp"
file9="Y_Universe.csv"

#check if Market Survey_YYMM.csv file is in working dir
if [ ! -e "$file3" ]
	then
	echo "Could not find $file3 in:"; pwd; exit
fi

#get rid of the heading, duplicates, sort by symbol and save
tail -n +2 "$file2" | sort -t, -k2,2 -u > "$file4"

#save possible incorrect symbols
if [ ! -e "$file1" ]
	then
	# Remove table heading and duplicate symbols. List dubious symbols:
	echo "Possible incorrect symbols:\n"
	grep -v -E "^[[:alnum:][:space:]\!?*'&/.-]*,[A-Z]{1,}," "$file4" > "$file1"
	cat "$file1"
	exit
fi

#rearrange fields to match the existing Market Survey_YYMM.csv, remove /r from the sector field
awk -F, -v OFS=, '{print $2, $1, $3, $4, $5, $6}' "$file4" | tr -d '\r' > temp; mv temp "$file4"

#strip Markey Survey_1601.csv of headings, duplicates, sort by symbol and save
tail -n +2 "$file3" | head -n -1 | sort -t, -k1,1 -u > temp; mv temp "$file7"

#extract symbols from the new universe:
awk -F, -v OFS=, '{print $1}' "$file4" > "$file5"
#extract symbols from the old universe:
awk -F, -v OFS=, '{print $1}' "$file7" > "$file6"
#show difference side by side
echo "Changes:"
echo "New     Old"
diff -y -w "$file5" "$file6"

#reveal new symbols:
diff -w --suppress-common-lines "$file5" "$file6" | grep "^<" | sed "s/< /^/g" > "$file8"

#join the new symbols with the Market Survey_YYMM.csv
join -a1 -t, -o "1.1,1.2,1.3,1.4,1.5,1.6,2.7,2.8,2.9,2.10,2.11" "$file4" "$file7" > "$file9"

#print out outro
echo "List of symbols for the new universe:" "$file5"
echo "List of symbols present in the new universe and absent in the old one: " "$file8"
echo "Revised Y_Universe file (data fields only): " "$file9"
echo "Delete this file to list the possible bad symbols: " "$file1"
echo "You can also remove all .tmp files now to keep the current dir clean"