services:
  App\Service\Exchange\Equities\NYSE:
    public: true
    autowire: true
  App\Service\Exchange\Equities\NASDAQ:
    public: true
    autowire: true
  App\Service\PriceHistory\OHLCV\Yahoo:
    public: true
    autowire: true
  App\Service\Scanner\OHLCV\Scanner:
    public: true
    autowire: true
  App\Service\ExpressionHandler\OHLCV\Calculator:
      public: true
      autowire: true
      arguments:
        $resultCacheLifetime: '%result_cache_lifetime%'
  App\Service\Exchange\DailyIterator:
    public: true
    autowire: true
  App\Service\Exchange\WeeklyIterator:
    public: true
    autowire: true
  App\Service\Exchange\MonthlyIterator:
    public: true
    autowire: true
  App\Service\Charting\OHLCV\Chart:
    public: true
    autowire: true
  App\Service\Exchange\Catalog:
    public: true
    autowire: true
  App\Service\Charting\OHLCV\StyleLibrary:
    public: true
    autowire: true
  App\Service\Watchlist\Factory:
    public: true
    autowire: true
  App\Studies\MGWebGroup\MarketSurvey\StudyBuilder:
    public: true
    autowire: true
