services:
  App\Service\Exchange\Equities\NYSE:
    public: true
    autowire: true
  App\Service\Exchange\Equities\NASDAQ:
    public: true
    autowire: true
  App\Service\PriceHistory\OHLCV\Yahoo:
    public: true
    autowire: true
  App\Service\Scanner\OHLCV\Scanner:
    public: true
    autowire: true
  App\Service\Scanner\OHLCV\ScannerExpression:
      public: true
      autowire: true
  App\Service\Exchange\DailyIterator:
    public: true
    autowire: true
  App\Service\Exchange\WeeklyIterator:
    public: true
    autowire: true
  App\Service\Exchange\MonthlyIterator:
    public: true
    autowire: true