parameters:
    # Dates for price history
    # '2000-01-01 Saturday'
    dates_begin: 946684800
    # '2100-12-31 Friday'
    dates_end: 4133894400
    # Doctrine cache validity
    result_cache_lifetime: 0

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Inject into console commands Monolog service that logs into channel 'th'.
    # Channel 'th' is specified in config/packages/{dev,prod}/monolog.yaml
    App\Command\:
        resource: '../src/Command/*'
        bind:
            Psr\Log\LoggerInterface: '@monolog.logger.th'
    # Drop %context% and %extra% fields from console onscreen output
    custom.formatter.line:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%%\n"

    Scheb\YahooFinanceApi\ApiClient:
        factory: ['Scheb\YahooFinanceApi\ApiClientFactory', 'createApiClient']
    app.price_provider:
        class: App\Service\PriceHistory\OHLCV\Yahoo

    App\Service\Exchange\DailyIterator:
        arguments:
            $start: '%dates_begin%'
            $end: '%dates_end%'

    App\Command\SyncPrice:
        arguments:
            $priceProvider: '@app.price_provider'

    App\Service\ExpressionHandler\OHLCV\Calculator:
        arguments:
            $resultCacheLifetime: '%result_cache_lifetime%'

    App\Service\Charting\OHLCV\StyleLibrary:
        arguments:
            $projectRootDir: '%kernel.project_dir%'
